### ISSUE TITLE
SHA+GCL MultiGPU Training

### ISSUE THREAD

**Issue by zhanwenchen** [rafa-cxg/PySGG-cxg#3]
On your README.md you said 

> Support multi-gpu on SHA model

How were you able to do that? What was the cause of the lack of support, and how did you solve it? I've been stuck with this issue with the SHA+GCL repo: #dongxingning/SHA-GCL-for-SGG#8.

**Comment by rafa-cxg** [comment]
Hi sorry for my late reply:
I do not know why the authors of SHA do not add SHA into PYSGG, but that's understandable. The unbiased methods in SHA needed to add a few files from the original SHA codebase, you can run SHA in my code to get specific inspirations.
