### ISSUE TITLE
your e-mail?

### ISSUE THREAD

**Issue by ZHUXUHAN** [rafa-cxg/PySGG-cxg#4]
Hello, I'm concerned from the PENET issue that you are also following this project, may I ask if we can have some communication about the reproduction situation. In addition, I noticed your recent article LANDMARK, this work gives me great inspiration, I hope to communicate with you, can you leave your e-mail?

**Comment by rafa-cxg** [comment]
Hi, sorry for late reply. My e-mail is 424400878@qq.com.
